-- migration-014: 软删除支持
-- 为所有可删除的表添加 deleted 列

ALTER TABLE category ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE product ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE case_info ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE enquiry ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE customer ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE supplier ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE commodity ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE commodity_category ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE product_type ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE pricing_formula ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE after_sale_order ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE sale_order ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE sale_order_item ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE purchase_order ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE purchase_order_item ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE sale_return ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE sale_return_item ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE purchase_return ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE purchase_return_item ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE stock_in ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE stock_in_item ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE stock_out ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE stock_out_item ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
ALTER TABLE payment ADD COLUMN deleted TINYINT NOT NULL DEFAULT 0;
